name: model-training
on: [push]
jobs:
  run:
    runs-on: [self-hosted, cml, gpu]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Train MNIST model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WANDB_LOGIN_TOKEN: ${{secrets.WANDB_LOGIN}}
        run: |
          pip install -r requirements.txt
          wandb login $WANDB_LOGIN_TOKEN
          python main.py
